footer/urls.py
from django.urls import path
from . import views

app_name = "community"

urlpatterns = [
    path('contact/', views.contact, name='contact'), 
    path('about/', views.about, name='about'),  
    

]

neighbouhood/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views

admin.site.site_header = settings.ADMIN_SITE_HEADER


urlpatterns = [
    path('admin/site/', admin.site.urls), 
    path('', include('myhood.urls', namespace='myhood')), 
    path('account/register/', user_views.register, name='register'),
    path('account/profile-update/',user_views.updateProfile,name='profile-update'),
    path('account/follow-unfollow/<int:pk>/',user_views.userFollowUnfollow,name="follow-unfollow"),
    path('account/password-change/', user_views.change_password, name='change-password'),
    path('accounts/login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'), 
    path('account/logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),  
    path('account/password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),  
    path('account/password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),  
    path('account/password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),  
    path('account/password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),  
    path('account/community/', include('footer.urls', namespace='community')),
    path('<str:username>/', user_views.profile, name='profile'),
    path('validate/username/', user_views.validate_username,name='validate-username'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'footer.views.error_404_view'

footer/models.py
from django.db import models
from django.utils import timezone

class Contact(models.Model):
	full_name = models.CharField(max_length=30)
	email = models.EmailField()
	message = models.TextField()
	date = models.DateTimeField(default=timezone.now)
	
	def __str__(self):
		return self.full_name


class Quote(models.Model):
	quote= models.TextField()
	date = models.DateTimeField(default=timezone.now)
	def __str__(self):
		return self.quote

footer/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
	class Meta:
		model = Contact
		fields = ['full_name','email','message']

footer/views.py
from django.shortcuts import render
from .forms import ContactForm



# Create your views here.

def contact(request):

	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			form.save()
			message = "Your Message/Feedback is sent, we will contact you soon. Thank You."
			return render(request,'footer/contact.html',{'message':message})
	else:
		form = ContactForm()
		context = {'form':form}
		return render(request,'footer/contact.html',context)

def about(request):
	return render(request,'footer/about.html')

def error_404_view(request,exception):
	return render(request,'footer/404.html')

footer/templates/footer/about.html
{% extends "blog/base.html" %}
 {% block title %}
   <title>About</title> 
 {% endblock %}
{% block content %}
<div class="content-section">
	<h1>Dave Mathaga</h1>
	<p>An avid learner of programming and life</p>
	<a href="https://github.com/davospots">Click to see github profile</a>

</div>
{% endblock content %}

footer/templates/footer/contact.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %} 
 {% block title %}
   <title>Contact - InstaClone</title> 
 {% endblock %}
 {% block content %}

<div class="content-section">

	{% if message %}
		<p>{{message}}</p>
	{% else %}
		<form method="POST">
	        {% csrf_token %}
	        <fieldset class="form-group">
	            <legend class="border-bottom mb-4">Contact</legend>
	            <p>Message, Quries and Feedbacks are welcome.</p>
	            {{ form|crispy }}
	        </fieldset>
	        <div class="form-group">
	            <button class="btn btn-outline-info btn-sm" type="submit">Send</button>
	        </div>
	    </form>
	{% endif %}
</div>

{% endblock content %}

footer/templates/footer/contribute.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %} 
 {% block title %}
   <title>Contribute - nccbuddy.com</title> 
 {% endblock %}
 {% block content %}

<div class="content-section">

	<h1>Contribute</h1>
	<ul>
		<li>nccbuddy.com is actively looking for contributors 
			 in various areas mentioned below
			<ol>
				<li>Web Developers or Designers</li>
				<li>Graphics Designers</li>
				<li>Artists</li>
				<li>Content Writers</li>
				<li>In other way you can.</li>
			</ol>
		</li>
		<li>To contribute mail us at nccbuddiesofficial@gmail.com.</li>
		<li>Please be specific in your mail and attach past work samples also.</li>
	</ul>

</div>

{% endblock content %}

footer/templates/footer/guidelines.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %} 
 {% block title %}
   <title>Guideline</title> 
 {% endblock %}
 {% block content %}

<div class="content-section">

	

</div>

{% endblock content %}

footer/templates/footer/sponsor.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %} 
 {% block title %}
   <title>Sponsor - "nccbuddy.com"</title> 
 {% endblock %}
 {% block content %}

<div class="content-section">

	<h1>Sponsor</h1>
	<ul>
		<li>For sponsoring and ads contact us(<a href="{% url 'community:contact' %}">click here</a>).
		</li>
	</ul>

</div>

{% endblock content %}