footer/urls.py
from django.urls import path
from . import views

app_name = "community"

urlpatterns = [
    path('contact/', views.contact, name='contact'), 
    path('about/', views.about, name='about'),  
    

]

myhood/urls.py
from django.urls import path
from . import views

app_name = "myhood"

urlpatterns = [
    path('', views.home_view, name='home'),  
    path('posts/<slug:slug>/',views.post_detail_view,name='post-detail'),  
    path('post/new/',views.post_create_view,name='post-create'),
    path('post/<int:pk>/update/', views.post_update_view, name='post-update'),  
    path('post/<int:pk>/delete/',views.post_delete_view, name='post-delete'), 
    path('search/', views.search_view, name='search'), 
    path('like/post',views.like_view,name='like'),
    path('report/post/',views.post_report_view,name='report'),
    path('report/user/',views.user_report_view,name='report-user'),
    path('<str:username>/notifications/',views.notifications_view,name='notifications'),
    path('<str:username>/notifications/update/',views.notifications_update_view,name='notifications-update'),
    path('<str:username>/notifications/count/',views.notifications_unread_count_view,name='notifications-count'),
]

neighbouhood/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views

admin.site.site_header = settings.ADMIN_SITE_HEADER


urlpatterns = [
    path('admin/site/', admin.site.urls), 
    path('', include('myhood.urls', namespace='myhood')), 
    path('account/register/', user_views.register, name='register'),
    path('account/profile-update/',user_views.updateProfile,name='profile-update'),
    path('account/follow-unfollow/<int:pk>/',user_views.userFollowUnfollow,name="follow-unfollow"),
    path('account/password-change/', user_views.change_password, name='change-password'),
    path('accounts/login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'), 
    path('account/logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),  
    path('account/password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),  
    path('account/password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),  
    path('account/password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),  
    path('account/password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),  
    path('account/community/', include('footer.urls', namespace='community')),
    path('<str:username>/', user_views.profile, name='profile'),
    path('validate/username/', user_views.validate_username,name='validate-username'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'footer.views.error_404_view'

myhood/models.py
# Third party imports.
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from PIL import Image
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill,Transpose
from django.db.models.signals import post_save,pre_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(null=True,unique=True,max_length=111)
    content =  models.TextField()
    image =  models.ImageField(upload_to='post_images')
    image_thumbnail = ImageSpecField(source='image',
                                      processors=[ 
                                        Transpose(),
                                        ResizeToFill(1000, 500)
                                        ],
                                      format='JPEG',
                                      options={'quality': 70})

    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='likes',blank=True)
    tagged_users = models.ManyToManyField(User, related_name='tagged_users',blank=True)

    @property
    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return self.title

            
    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'slug': self.slug})


REASON = [
    
    ('SPAM','SPAM'),
    ('INAPPROPRIATE','INAPPROPRIATE'),
    
]


class PostReport(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    reason = models.CharField(max_length=20,choices=REASON)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    date_reported = models.DateTimeField(default=timezone.now) 

    def __str__(self):
        return self.post.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.comment

class Business(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    description = models.CharField(max_length=100)


class Notification(models.Model):
    sender = models.ForeignKey(User,on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User,on_delete=models.CASCADE, related_name='receiver')
    post = models.ForeignKey(Post,on_delete=models.CASCADE,null=True)
    action = models.CharField(max_length=50, blank=True)
    read = models.BooleanField(default=False)    
    timestamp = models.DateTimeField(default=timezone.now)


# SIGNALS
@receiver(post_save,sender=Post)
def post_mentioned_notify(sender, instance, *args, **kwargs):
    sender = User.objects.get(pk=instance.author.pk)
    post = Post.objects.get(pk=instance.pk)
    string = instance.content
    poss_users = [i  for i in string.split() if i.startswith("@")]
    poss_users_list = []
    for user in poss_users:
        poss_users_list.append(user[1:])

    for username in poss_users_list:
        try:
            get_user = User.objects.get(username=username)
        except:
            continue
        if get_user in instance.tagged_users.all():
            continue
        elif get_user == sender:
            continue
        else:
            instance.tagged_users.add(get_user)
            notify = Notification.objects.create(sender=sender,receiver=get_user,post=post,action="mentioned you in post")


@receiver(post_save,sender=Comment)
def comment_added_notify(sender, instance, *args, **kwargs):
    sender = User.objects.get(pk=instance.author.pk)
    post = Post.objects.get(pk=instance.post.pk)
    receiver = User.objects.get(pk=instance.post.author.pk)
    if receiver == sender:
        pass
    else:
        notify = Notification.objects.create(sender=sender,receiver=receiver,post=post,action="commented on your post")


@receiver(pre_save,sender=Post)
def sulg_generator(sender, instance, *args, **kwargs):
    instance.slug = slugify(instance.title+" "+str(sender.objects.count()))

myhood/forms.py
from django import forms

from .models import Comment, PostReport, Post ,Business

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['title','content','image']

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['comment']

class ReportPostForm(forms.ModelForm):
	class Meta:
		model = PostReport
		fields = ['reason']


class BusinessForm(forms.ModelForm):
	class Meta:
		model = Business
		fields = ['name','email','description']

myhood/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404,redirect
from django.db.models import Q
from django.http import HttpResponse,JsonResponse
try:
    from django.utils import simplejson as json
except ImportError:
    import json
import random

from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Post, Comment, PostReport, Notification
from users.models import UserReport
from users.models import Profile
from .forms import CommentForm, ReportPostForm, PostForm


@login_required
def home_view(request):
    user = request.user

    if user.is_authenticated:
        follows_users = user.profile.follows.all()
        follows_posts = Post.objects.filter(author_id__in=follows_users)
        user_posts = Post.objects.filter(author=user)
        post_list = (follows_posts|user_posts).distinct().order_by('-date_posted')
        page = request.GET.get('page', 1)
        paginator = Paginator(post_list, 4)
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)

        context = {
                    'posts': posts,

            }
        return render(request, 'hood/home.html', context)
    else:
        return redirect('login')

def post_detail_view(request,slug=None):
    post = get_object_or_404(Post, slug=slug)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post=post
            comment.author=request.user
            comment.save()
            return redirect('hood:post-detail', slug=post.slug)
    else:
        form = CommentForm()
        report_form = ReportPostForm()
        comments = Comment.objects.filter(post=post).order_by('-id')
        context = {'post':post,'form':form,'comments':comments,'report_form':report_form}

    return render(request,'hood/post_detail.html',context)

    
@login_required
def post_create_view(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author=request.user
            post.save()
            ctx = {'url':post.get_absolute_url()}
            return HttpResponse(json.dumps(ctx), content_type='application/json')

    else:
        form = PostForm()
        context = {
            'form': form,
        }
        return render(request,'hood/post_form.html',context)


@login_required
def post_update_view(request,pk):
    post1 = get_object_or_404(Post,pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES,instance=post1)
        if form.is_valid():
            post=form.save(commit=False)
            post.author = request.user
            post.save()
            ctx = {'url':post.get_absolute_url()}
            return HttpResponse(json.dumps(ctx), content_type='application/json')
    else:
        post = get_object_or_404(Post,pk=pk)
        form = PostForm(instance = post)
        context = {
            'form': form,
            'post':post,
        }
        return render(request,'hood/post_form_update.html',context)

@login_required
def post_delete_view(request, pk=None):
    context = {}
    post = get_object_or_404(Post,pk=pk)
    
    if request.method =="POST":
        if post.author == request.user:
            post.delete()
            return redirect('profile', username=request.user.username)
    context = {"post":post}
    return render(request,'hood/post_confirm_delete.html',context)



@login_required
def search_view(request):
    
    message = ""
    post_list = Post.objects.all().order_by('-pk');
    page = request.GET.get('page', 1)
    paginator = Paginator(post_list, 4)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    
    if request.method == 'POST':
        try:
            search_input = request.POST.get('search')
            result_posts = Post.objects.filter(Q(title__icontains=search_input)|Q(content__icontains=search_input))
            users = User.objects.filter(Q(username__iexact=search_input))

            # first condition : post-0 , users-0
            if result_posts.count() == 0 and users.count() == 0:
                message = "No results found for: "+search_input
                context = {'message':message,'posts':posts,'search_input':search_input}
                return render(request,'hood/search.html',context)

            # second condition : post-yes , users-0
            elif users.count() == 0 and result_posts.count() != 0:
                context = {'result_posts':result_posts,'search_input':search_input,'posts':posts}
                return render(request,'hood/search.html',context)

            # 3rd condition : post-no , users-yes
            elif result_posts.count() == 0 and users.count() > 0:
                context = {'users':users,'posts':posts,'search_input':search_input}
                return render(request,'hood/search.html',context)
            
            # 4th condition : post:yes , user: yes
            else:
                context = {'users':users,'result_posts':result_posts,'posts':posts,'search_input':search_input}
                return render(request,'hood/search.html',context)

        except:
            message = "Unexpected Error Occured!"
            context = {'message':message}
            return render(request,'hood/search.html',context)
    else:
        flag = True
        context = {'posts':posts,'flag':flag}
        return render(request,'hood/search.html',context)


@login_required
@require_POST
def like_view(request):
    if request.method == 'POST':
        user = request.user
        pk = request.POST.get('pk', None)
        post = get_object_or_404(Post, pk=pk)

        if post.likes.filter(id=user.id).exists():
            post.likes.remove(user)
            like = False
            post_id = '#like'+str(post.id)
        else:
            post.likes.add(user)
            like = True
            post_id = '#like'+str(post.id)
           
    ctx = {'likes_count': post.total_likes,'like':like,'post_id':post_id}
    return HttpResponse(json.dumps(ctx), content_type='application/json')


@login_required
@require_POST
def post_report_view(request):
    if request.method == 'POST':
        pk = request.POST.get('pk',None)
        reason = request.POST.get('reason')
        post=get_object_or_404(Post,pk=pk)
        user=request.user
        report = PostReport(post=post,reason=reason,user=user)
        report.save()

        return HttpResponse('')

@login_required
@require_POST
def user_report_view(request):
    if request.method == 'POST':
        pk = request.POST.get('pk',None)
        reason = request.POST.get('reason')
        reported_user=get_object_or_404(User,pk=pk)
        report = UserReport(reported_user=reported_user,reason=reason,reporting_user=request.user)
        report.save()

        return HttpResponse('')

@login_required
def notifications_view(request,username=None):
    user = get_object_or_404(User,username=username)
    notifications = Notification.objects.filter(receiver=user).order_by('-timestamp')
    page = request.GET.get('page', 1)
    paginator = Paginator(notifications, 6)
    try:
        notifications = paginator.page(page)
    except PageNotAnInteger:
        notifications = paginator.page(1)
    except EmptyPage:
        notifications = paginator.page(paginator.num_pages)

    return render(request,'hood/notifications.html',{'notifications':notifications})

@login_required
def notifications_update_view(request,username=None):
    user = get_object_or_404(User,username=username)
    if user == request.user:
        notifications = Notification.objects.filter(receiver=user)
        for notification in notifications.all():
            if notification.read == False:
                notification.read = True
                notification.save()
        return HttpResponse('')


@login_required
def notifications_unread_count_view(request,username=None):
    user = get_object_or_404(User,username=username)
    if user == request.user:
        notifications = Notification.objects.filter(receiver=user)
        count = 0
        for notification in notifications.all():
            if notification.read == False:
                count = count+1
        data = {
            'count':count
        }
        return JsonResponse(data)

myhood/templates/hood/home.html
{% extends "hood/base.html" %}
{% load static %}
{% block title %}
  <title>Neighbourhood</title>
{% endblock %}
{% block content %}
<div class="infinite-container">
  {% for post in posts %}
    <article class="media content-section infinite-item">
      <img class="rounded-circle article-img" src="{{ post.author.profile.image_thumbnail_user.url }}">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2"
               href="{% url 'profile' post.author.username %}">{{ post.author }}
            </a>
            <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}
            </small>
          </div>
          <div class="img-heading-wrap">
            <div class="article-post-img">
              <img class="post-img" src="{{post.image_thumbnail.url}}">
            </div>
            <p class="h-font">
              <a class="article-title"
                   href="{% url 'myhood:post-detail' post.slug %}">{{ post.title }}
                </a>
            </p>              
          </div>
          <p class="article-content">{{ post.content|truncatewords:30}}</p>
          <a class="read-more" href="{% url 'myhood:post-detail' post.slug %}"><small>Read More</small></a>
         
        </div>
      </article>
    {% empty %}
      {% include "hood/no_posts_home.html" %}
    {% endfor %}
  </div>
  <div class="loading" style="display: none;">
    Loading...
    <br>
  </div>
  {% if posts.has_next %}
    <a class="infinite-more-link" style="display: none;" href="?page={{ posts.next_page_number }}">More</a>
  {% endif %}
{% endblock content %}

{% block script %}
      <script>
          var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            onBeforePageLoad: function () {
              $('.loading').show();
            },
            onAfterPageLoad: function ($items) {
              $('.loading').hide();
            }
          });
      </script>
{% endblock %}

myhood/templates/hood/no_posts_home.html
{% load static %}

<section>
	<div class="">
	  <div class="">
	    Welcome <b>{{user.username}}</b>
	  </div>
	  <div class="card-body">
	    <p class="card-text">Place to find all alerts within your hood.</p>
	    <p class="card-text">To add or update your personal information <a href="{% url 'profile-update' %}">click here</a>.</p>
	    <p>You can also search for alerts and posts at <a href="{% url 'myhood:search' %}">search</a> page.</p>
	    <p>To add your first post click the button below.</p>
	    <a href="{% url 'myhood:post-create' %}" class="btn btn-primary">Add Post</a>
		<a href="" data-toggle="tooltip" title="Add Post">
			<button type="button" class="btn btn-primary btn-sm">Add Business</button>
		</a>
		
		<a href="" data-toggle="tooltip" title="Add Post">
			<button type="button" class="btn btn-primary btn-sm">Add Contacts</button>
		</a>
	  </div>
	</div>
	<br>
</section>

myhood/templates/hood/notifications.html
{% extends "hood/base.html" %}
{% block title %}<title> @{{request.user.username}}'s notifications- Neighbourhood</title>{% endblock %}

{% block content %}
      <div class="content-section overflow-auto infinite-container">
        <h1>ALERTS</h1>
        {% for notification in notifications %}
          {% if notification.read %}
          <p class="notification-list-items-read infinite-item">
          {%else%}
          <p class="notification-list-items-unread infinite-item">
          {% endif %}

            <a href="{% url 'profile' notification.sender.username %}" style="text-decoration: blink;">{{notification.sender.username}}</a> {{notification.action}} 
            {% if notification.post %}
             <span class="post-title-notify"><a href="{% url 'myhood:post-detail' notification.post.slug %}">"{{notification.post.title}}".</a></span>
            {% endif %}
             <br><small>({{notification.timestamp|date:"D, d M, g:i a"}})</small>
          </p>
        {% empty %}
        <p class="notification-list-items-unread">No alerts yet! Welcome to Neighbourhood</p>
        {% endfor %}
      </div>

      <div class="loading" style="display: none;">
        Loading...
      </div>
      {% if notifications.has_next %}
        <a class="infinite-more-link" style="display: none;" href="?page={{ notifications.next_page_number }}">More</a>
      {% endif %}
      
{% endblock content %}
{% block script %}
        <script>
        $( document ).ready(function(){
            $.ajax({
                url: "{% url 'myhood:notifications-update' request.user.username %}",
                type: 'get',
                success: function(data){
                },
                error: function (xhr, ajaxOptions, thrownError) {
                  }
            });
        });
        </script>
        <script>
          var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            onBeforePageLoad: function () {
              $('.loading').show();
            },
            onAfterPageLoad: function ($items) {
              $('.loading').hide();
            }
          });
      </script>

{% endblock %}

myhood/templates/hood/post_confirm_delete.html
 {% extends "hood/base.html" %} 
 {% block title %}
   <title>Confirm delete * {{post.title}} - Neighbourhood</title> 
 {% endblock %}
 {% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete Post</legend>
            <h5>Are you sure you want to delete the post?</h5>
            <h3>"{{ post.title }}"</h3>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger btn-sm" type="submit">Yes, Delete
            </button>
            <a class="btn btn-outline-secondary btn-sm"
               href="{% url 'myhood:post-detail' post.id %}">Cancel
            </a>
            <br><small>Once post deleted there is now way it can be bring back.</small>
        </div>
    </form>
</div>
{% endblock content %}

myhood/templates/hood/post_detail.html
{% extends "hood/base.html" %}

{% load crispy_forms_tags %}

{% block meta %}
  <meta name="description" content={{post.title}}>
{% endblock %}


{% block title %}<title> {{post.title}} - Neighbourhood</title>{% endblock %}

{% block content %}
  <article class="content-section-details">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2"
           href="{% url 'profile' post.author.username %}"><span class="link-style-none">Post by: </span> {{ post.author }}
        </a>
        <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
        {% if not post.author == user %}
        {% if user.is_authenticated %}
        <a data-target="#ReportModalCenter" data-toggle="modal" class="report-dots">
          <div class="" style="float: right;">
            <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
            width="24" height="24"
            viewBox="0 0 172 172"
            style=" fill:#000000;"><g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><path d="M0,172v-172h172v172z" fill="none"></path><g fill="#cccccc"><path d="M43,71.66667c-7.91608,0 -14.33333,6.41725 -14.33333,14.33333c0,7.91608 6.41725,14.33333 14.33333,14.33333c7.91608,0 14.33333,-6.41725 14.33333,-14.33333c0,-7.91608 -6.41725,-14.33333 -14.33333,-14.33333zM86,71.66667c-7.91608,0 -14.33333,6.41725 -14.33333,14.33333c0,7.91608 6.41725,14.33333 14.33333,14.33333c7.91608,0 14.33333,-6.41725 14.33333,-14.33333c0,-7.91608 -6.41725,-14.33333 -14.33333,-14.33333zM129,71.66667c-7.91608,0 -14.33333,6.41725 -14.33333,14.33333c0,7.91608 6.41725,14.33333 14.33333,14.33333c7.91608,0 14.33333,-6.41725 14.33333,-14.33333c0,-7.91608 -6.41725,-14.33333 -14.33333,-14.33333z"></path></g></g></svg>
          </div>
        </a>
        {% endif %}
        {% endif %}
      </div>
      {% if post.author == user %}
          <div>
            <a class="btn btn-outline-secondary btn-sm mt-1 mb-1"
               href="{% url 'myhood:post-update' post.id %}">Update
            </a>
            <a class="btn btn-outline-danger btn-sm mt-1 mb-1"
               href="{% url 'myhood:post-delete' post.id %}">Delete
            </a>
          </div>
          
      {% endif %}
    </div>

  </article>
  <article class="media">
    <div class="media-body">
      <h1 class="article-title">{{ post.title }}</h1>
      <hr>
      <img class="post-image-detail" src="{{post.image.url}}">
      <br>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  
  

  
  
</div>

<div class="modal fade" id="ReportModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Report Post</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" style="overflow: hidden;">
        <form action="{% url 'myhood:report' %}" method="POST" id="report-form" name="{{post.id}}">
          {% csrf_token %}
          {{report_form | crispy}}
          <button type="submit" class="btn btn-outline-primary" style="float: right;">Report</button>
        </form>
        <p id="report-message" style="display: none;">Your response has been reported.</p>
      </div>
    </div>
  </div>
</div>


{% endblock content %}

{% block script %}
{% if user in post.likes.all %}
<script>
    $(document).ready(function () {
      $('#unliked').hide()
    });
</script>
{% else %}
<script type="text/javascript">
    $(document).ready(function () {
      $('#liked').hide()
    });
</script>
{% endif %}

<script>
$(document).ready(function () {
$('.like').click(function(event){
      event.preventDefault();
      $.ajax({
               type: "POST",
               url: "{% url 'myhood:like' %}",
               data: {'pk': $(this).attr('name'), 'csrfmiddlewaretoken': '{{ csrf_token }}'},
               dataType: "json",
               success: function(response) {
                      if (response.like) {
                        $('#liked').show();
                        $('#unliked').hide();
                        $('#like-count').text(response.likes_count);

                      } else {
                        $('#liked').hide();
                        $('#unliked').show();
                        $('#like-count').text(response.likes_count);
                      }
                },

                error: function(rs, e) {
                       alert('Poor network try again or refresh the page.');


                }
          }); 
    });
});
</script>
<script type="text/javascript">
$(document).ready(function () {

$('#report-form').on('submit',function(event){

    event.preventDefault();
    $.ajax({
      url: "{% url 'myhood:report' %}",
      type: "POST",
      data: {'reason':$('#id_reason').val(),'pk': $(this).attr('name'),'csrfmiddlewaretoken': '{{ csrf_token }}'},
      success: function(response) {
            
              $('#report-form').hide();
              $('#report-message').show();

          },
      error: function(rs, e) {
            $('#report-form').hide();
            $('#report-message').show();
          },
    })
    
});


});
  
</script>

<script type="text/javascript">
  $(document).ready(function(){
    $(".article-content").each(function(data){
      var UserReg = /(^|\s)@([\w\d-]+)/g
      var NewText = $(this).html().match(UserReg, "$1<a href='/$2/'>@$2</a>")
      var NewText = $(this).html().replace(UserReg, "$1<a href='/$2/'>@$2</a>")
      $(this).html(NewText)
    })
  })
</script>
<script type="text/javascript">
  $(document).ready(function(){
    $(".article-content").each(function(data){
      var LinkReg = /(https?:\/\/[^\s]+)/g;
      var LinkText = $(this).html().match(LinkReg)
      var LinkText = $(this).html().replace(LinkReg, "<a href="+LinkText+">"+LinkText+"</a>")
      $(this).html(LinkText)
    })
  })
</script>
{% endblock %}